version: 2

updates:
  - package-ecosystem: nuget
    directory: /
    open-pull-requests-limit: 10
    schedule:
      interval: daily
      time: "12:00"
      timezone: "Europe/London"
    # Single PR for patch and minor
    # Major will be one update per PR
    # AWS SDK updates no matter what update type
    groups:
      patch:
        update-types:
          - "patch"
      minor:
        update-types:
          - "minor"
      aws-sdk:
        patterns:
          - "AWSSDK.*"
    allow:
      - dependency-type: direct

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: "12:00"
      timezone: "Europe/London"