//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable


using System.Text.Json.Serialization;



namespace Defra.TradeImportsData.Domain.IPaffs;

/// <summary>
/// Catch certificate attachment
/// </summary>
public partial class CatchCertificateAttachment  //
{


    /// <summary>
    /// The UUID of the uploaded catch certificate file in blob storage
    /// </summary>
    
    [JsonPropertyName("attachmentId")]
    [System.ComponentModel.Description("The UUID of the uploaded catch certificate file in blob storage")]
    public string? AttachmentId { get; set; }


    /// <summary>
    /// The total number of catch certificates on the attachment
    /// </summary>
    
    [JsonPropertyName("numberOfCatchCertificates")]
    [System.ComponentModel.Description("The total number of catch certificates on the attachment")]
    public int? NumberOfCatchCertificates { get; set; }


    /// <summary>
    /// List of catch certificate details
    /// </summary>
    
    [JsonPropertyName("catchCertificateDetails")]
    [System.ComponentModel.Description("List of catch certificate details")]
    public CatchCertificateDetails[]? CatchCertificateDetails { get; set; }

}