//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable


using System.Text.Json.Serialization;



namespace Defra.TradeImportsData.Domain.IPaffs;
public partial class CatchCertificates  //
{


    /// <summary>
    /// The catch certificate number
    /// </summary>
    
    [JsonPropertyName("certificateNumber")]
    [System.ComponentModel.Description("The catch certificate number")]
    public string? CertificateNumber { get; set; }


    /// <summary>
    /// The catch certificate weight number
    /// </summary>
    
    [JsonPropertyName("weight")]
    [System.ComponentModel.Description("The catch certificate weight number")]
    public double? Weight { get; set; }

}