//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable


using System.Text.Json.Serialization;



namespace Defra.TradeImportsData.Domain.IPaffs;
public partial class CommonUserCharge  //
{


    /// <summary>
    /// Indicates whether the last applicable change was successfully send over the interface to Trade Charge
    /// </summary>
    
    [JsonPropertyName("wasSentToTradeCharge")]
    [System.ComponentModel.Description("Indicates whether the last applicable change was successfully send over the interface to Trade Charge")]
    public bool? WasSentToTradeCharge { get; set; }

}