//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable


using System.Text.Json.Serialization;



namespace Defra.TradeImportsData.Domain.IPaffs;

/// <summary>
/// Details on re-export
/// </summary>
public partial class DetailsOnReExport  //
{


    /// <summary>
    /// Date of re-export
    /// </summary>
    
    [JsonPropertyName("date")]
    [System.ComponentModel.Description("Date of re-export")]
    public DateOnly? Date { get; set; }


    /// <summary>
    /// Number of vehicle
    /// </summary>
    
    [JsonPropertyName("meansOfTransportNo")]
    [System.ComponentModel.Description("Number of vehicle")]
    public string? MeansOfTransportNo { get; set; }


    /// <summary>
    /// Type of transport to be used
    /// </summary>
    
    [JsonPropertyName("transportType")]
    [System.ComponentModel.Description("Type of transport to be used")]
    [MongoDB.Bson.Serialization.Attributes.BsonRepresentation(MongoDB.Bson.BsonType.String)]
    public DetailsOnReExportTransportTypeEnum? TransportType { get; set; }


    /// <summary>
    /// Document issued for re-export
    /// </summary>
    
    [JsonPropertyName("document")]
    [System.ComponentModel.Description("Document issued for re-export")]
    public string? Document { get; set; }


    /// <summary>
    /// Two letter ISO code for country of re-dispatching
    /// </summary>
    
    [JsonPropertyName("countryOfReDispatching")]
    [System.ComponentModel.Description("Two letter ISO code for country of re-dispatching")]
    public string? CountryOfReDispatching { get; set; }


    /// <summary>
    /// Exit BIP (where consignment will leave the country)
    /// </summary>
    
    [JsonPropertyName("exitBip")]
    [System.ComponentModel.Description("Exit BIP (where consignment will leave the country)")]
    public string? ExitBip { get; set; }

}