//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable


using System.Text.Json.Serialization;



namespace Defra.TradeImportsData.Domain.IPaffs;

/// <summary>
/// Feedback information from control
/// </summary>
public partial class FeedbackInformation  //
{


    /// <summary>
    /// Type of authority
    /// </summary>
    
    [JsonPropertyName("authorityType")]
    [System.ComponentModel.Description("Type of authority")]
    [MongoDB.Bson.Serialization.Attributes.BsonRepresentation(MongoDB.Bson.BsonType.String)]
    public FeedbackInformationAuthorityTypeEnum? AuthorityType { get; set; }


    /// <summary>
    /// Did the consignment arrive
    /// </summary>
    
    [JsonPropertyName("consignmentArrival")]
    [System.ComponentModel.Description("Did the consignment arrive")]
    public bool? ConsignmentArrival { get; set; }


    /// <summary>
    /// Does the consignment conform
    /// </summary>
    
    [JsonPropertyName("consignmentConformity")]
    [System.ComponentModel.Description("Does the consignment conform")]
    public bool? ConsignmentConformity { get; set; }


    /// <summary>
    /// Reason for consignment not arriving at the entry point
    /// </summary>
    
    [JsonPropertyName("consignmentNoArrivalReason")]
    [System.ComponentModel.Description("Reason for consignment not arriving at the entry point")]
    public string? ConsignmentNoArrivalReason { get; set; }


    /// <summary>
    /// Date of consignment destruction
    /// </summary>
    
    [JsonPropertyName("destructionDate")]
    [System.ComponentModel.Description("Date of consignment destruction")]
    public string? DestructionDate { get; set; }

}