//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable


using System.Text.Json.Serialization;



namespace Defra.TradeImportsData.Domain.IPaffs;

/// <summary>
/// Result of risk assessment by the risk scorer
/// </summary>
public partial class RiskAssessmentResult  //
{


    /// <summary>
    /// List of risk assessed commodities
    /// </summary>
    
    [JsonPropertyName("commodityResults")]
    [System.ComponentModel.Description("List of risk assessed commodities")]
    public CommodityRiskResult[]? CommodityResults { get; set; }


    /// <summary>
    /// Date and time of assessment
    /// </summary>
    
    [JsonPropertyName("assessedOn")]
    [System.ComponentModel.Description("Date and time of assessment")]
    ////[Btms.Common.Json.UnknownTimeZoneDateTimeJsonConverter(nameof(AssessedOn)), MongoDB.Bson.Serialization.Attributes.BsonDateTimeOptions(Kind = DateTimeKind.Unspecified)]
    public DateTime? AssessedOn { get; set; }

}