//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable


using System.Text.Json.Serialization;



namespace Defra.TradeImportsData.Domain.IPaffs;

/// <summary>
/// Contains countries and transfer points that consignment is going through
/// </summary>
public partial class Route  //
{

    
    [JsonPropertyName("transitingStates")]
    public string[]? TransitingStates { get; set; }

}