//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable


using System.Text.Json.Serialization;



namespace Defra.TradeImportsData.Domain.IPaffs;

/// <summary>
/// Details of the seal check
/// </summary>
public partial class SealCheck  //
{


    /// <summary>
    /// Is seal check satisfactory
    /// </summary>
    
    [JsonPropertyName("satisfactory")]
    [System.ComponentModel.Description("Is seal check satisfactory")]
    public bool? Satisfactory { get; set; }


    /// <summary>
    /// reason for not satisfactory
    /// </summary>
    
    [JsonPropertyName("reason")]
    [System.ComponentModel.Description("reason for not satisfactory")]
    public string? Reason { get; set; }


    /// <summary>
    /// Official inspector
    /// </summary>
    
    [JsonPropertyName("officialInspector")]
    [System.ComponentModel.Description("Official inspector")]
    public OfficialInspector? OfficialInspector { get; set; }


    /// <summary>
    /// date and time of seal check
    /// </summary>
    
    [JsonPropertyName("checkedOn")]
    [System.ComponentModel.Description("date and time of seal check")]
    ////[Btms.Common.Json.UnknownTimeZoneDateTimeJsonConverter(nameof(CheckedOn)), MongoDB.Bson.Serialization.Attributes.BsonDateTimeOptions(Kind = DateTimeKind.Unspecified)]
    public DateTime? CheckedOn { get; set; }

}