//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable


using System.Text.Json.Serialization;



namespace Defra.TradeImportsData.Domain.IPaffs;

/// <summary>
/// Validation field code-message representation
/// </summary>
public partial class ValidationMessageCode  //
{


    /// <summary>
    /// Field
    /// </summary>
    
    [JsonPropertyName("field")]
    [System.ComponentModel.Description("Field")]
    public string? Field { get; set; }


    /// <summary>
    /// Code
    /// </summary>
    
    [JsonPropertyName("code")]
    [System.ComponentModel.Description("Code")]
    public string? Code { get; set; }

}